spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    enabled: ${APP_SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${APP_SWAGGER_ENABLED:false}

app:
  redis:
    enabled: ${APP_REDIS_ENABLED:true}
  security:
    permit-all: false
    swagger-enabled: ${APP_SWAGGER_ENABLED:false}
    username: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}
    cors:
      allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  front-origin: ${NEXT_ORIGIN}
  ai:
    base-url: ${AI_BASE_URL}
