package com.noono0.stock.risk.domain.enums;

/** 리스크·알림 이벤트 유형 */
public enum RiskEventType {
    DAILY_LOSS_LIMIT_REACHED,
    DAILY_LOSS_AMOUNT_REACHED,
    DAILY_TRADE_LIMIT_REACHED,
    TIME_WINDOW_TRADE_LIMIT,
    SYMBOL_POSITION_LIMIT,
    STRATEGY_POSITION_LIMIT,
    REENTRY_COOLDOWN,
    CONSECUTIVE_STOP_LOSS,
    STRATEGY_AUTO_DISABLED,
    MARKET_CRASH_BUY_HALT,
    API_ERROR_ORDER_HALT,
    QUOTE_DELAY_HALT,
    BUY_BLOCKED_WARNING,
    ORDER_VALIDATION_FAILED
}
